title: Una historia simple del mundo
description: Historia simple
remote_theme: poole/lanyon@v1.1.0
collections:
  capitulos:
    output: true
plugins:
- jekyll-remote-theme
- jekyll-include-cache
- jekyll-paginate

